### ISSUE TITLE
Port the ArgumentRecovery IR Pass

### ISSUE THREAD

**Issue by surovic** [trailofbits/fcd#11]
The pass attempts to recover function arguments for lifted IR functions. The pass heavily relies on information provided the `ParameterRegistry` class in fcd/callconv/param_registry.(h|cpp) and IR passes associated with it, namely `ParameterRegistryPass` and `ProgramMemoryAliasAnalysis`.

**Comment by pgoodman** [comment]
McSema has some stuff in it's ABI.cpp file(s) that may be relevant.

**Comment by surovic** [comment]
Implemented in #13
