### ISSUE TITLE
Reimplement the TranslationContext class using Remill

### ISSUE THREAD

**Issue by surovic** [trailofbits/fcd#3]
Title is pretty self-explanatory. Relevant code is in `fcd/codegen/translation_context.cpp`. This will also include changes to the users of TranslationContext. Code will be formatted using Remill's clang-format.

**Comment by pgoodman** [comment]
Note: I am not certain if Remill's clang-format file is correct. I generally use Eclipse's Google C++ XML file when I need to auto-format third-party code.

**Comment by surovic** [comment]
I could try using clang-format's default google preset. Do you think that would be a better idea?

**Comment by pgoodman** [comment]
Probably a good idea.

**Comment by surovic** [comment]
Implemented in #7
